version: 2
jobs:
  test-php73:
    docker:
      - image: circleci/php:7.3-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Lowest
          command: |
            composer update -n --prefer-dist --prefer-lowest --no-suggest
            rm -Rf var/*
            php vendor/bin/phpunit --testsuite=base

      - run:
          name: Run tests / Highest + No Stopwatch
          command: |
            composer require symfony/stopwatch:^5.0
            composer update -n --prefer-dist --no-suggest
            rm -Rf var/*
            php vendor/bin/phpunit --testsuite=no-stopwatch


  test-php74:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Highest
          command: |
            composer update -n --prefer-dist --no-suggest
            rm -Rf var/*
            php vendor/bin/phpunit --testsuite=base

workflows:
  version: 2
  test:
    jobs:
      - test-php73
      - test-php74