version: 2
jobs:
  test-php74-no-filesystem:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Lowest + Stopwatch
          command: |
            composer require symfony/stopwatch:^5.0 --no-update
            composer update -n --prefer-dist --no-suggest
            rm -Rf var/*
            php vendor/bin/phpunit --testsuite=with-stopwatch --exclude-group=with-filesystem

  test-php74-filesystem:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Highest
          command: |
            composer require react/filesystem:^0.1 --no-update
            composer update -n --prefer-dist
            rm -Rf var/*
            php vendor/bin/phpunit --testsuite=base --exclude-group=without-filesystem

  test-php80-no-filesystem:
    docker:
      - image: circleci/php:8.0-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Highest
          command: |
            composer update -n --prefer-dist
            rm -Rf var/*
            php vendor/bin/phpunit --testsuite=base --exclude-group=with-filesystem

workflows:
  version: 2
  test:
    jobs:
      - test-php74-no-filesystem
      - test-php74-filesystem
      - test-php80-no-filesystem