version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install PHPUnit
          command: |
            composer require phpunit/phpunit:7.5.17 --no-update

      - run:
          name: Run tests / Symfony 4^3
          command: |
            composer update -n --prefer-dist --prefer-lowest --no-suggest
            php vendor/bin/phpunit --testsuite=base

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit --testsuite=base

      - run:
          name: Run tests / No Stopwatch
          command: |
            composer require symfony/stopwatch:^5.0
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit --testsuite=no-stopwatch